name: 3step

on:
  schedule:
    - cron: 0 */3 * * *
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v2
      
      - name: Run
        run: bash start.sh
        
        env:
          LINK: ${{secrets.LINK}}
          LINK2: ${{secrets.LINK2}}
          LINK3: ${{secrets.LINK3}}
